### ISSUE TITLE
'make install' fails

### ISSUE THREAD

**Issue by gamebox** [egorFiNE/node-compress-buffer#4]
Trying to install a package that depends on log4js which depends on this module.  Here's the error report from npm:

npm ERR! compress-buffer@0.5.1 install: `make build`
npm ERR! `sh "-c" "make build"` failed with 2
npm ERR! 
npm ERR! Failed at the compress-buffer@0.5.1 install script.
npm ERR! This is most likely a problem with the compress-buffer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get their info via:
npm ERR!     npm owner ls compress-buffer
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.32-318-ec2
npm ERR! command "node" "/usr/bin/npm" "install" "node-foursquare-2"
npm ERR! cwd /home/ubuntu/shiftee
npm ERR! node -v v0.6.11
npm ERR! npm -v 1.1.2
npm ERR! code ELIFECYCLE
npm ERR! message compress-buffer@0.5.1 install: `make build`
npm ERR! message `sh "-c" "make build"` failed with 2
npm ERR! errno {}
npm ERR!

**Comment by jacek-berlin** [comment]
in debian package called "node" ist NOT nodejs.
